[workspace]
members=[]
resolver="3"

[workspace.package]
license = "MPL-2.0"
description = "Modern WASM compatibility layer and oS"

[workspace.dependencies]
portal-pc-waffle = "^0.5"
pit-core = "^0.4.2"
pit-patch = "^0.4.2"
awaiter-trait = "^0.2.7"
bysyncify = "^0.2.2"